DATAS SEGMENT
    LIST DW 05H,2H,4H,6H,8H,0A0H
	X DW 7H
	Infor DB ‘2012020028Fujingqi’
DATAS ENDS

STACKS SEGMENT

STACKS ENDS

CODES SEGMENT
    ASSUME CS:CODES,DS:DATAS,SS:STACKS
START:
    MOV AX,DATAS
    MOV DS,AX
    XOR AX,AX
    XOR CX,CX
    MOV SI,0
    MOV BX,0
    MOV CX,X
ABC:
    ADD SI,2
    INC BX
    MOV AX,[LIST][SI]
    CMP AX,CX
    JB ABC
    INC WORD PTR LIST
CD:
    MOV [LIST][SI],CX
    MOV CX,AX
    ADD SI,2
    MOV AX,[SI]
    INC BX
    CMP BX,WORD PTR LIST
    JNA CD
EXIT:
    MOV AH,4CH
    INT 21H
CODES ENDS
    END START
